# Generated by Django 5.2 on 2025-04-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0002_reporte_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabras',
            name='descripcion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='conteo',
            unique_together={('reporte', 'palabra')},
        ),
    ]
