# Generated by Django 5.2 on 2025-04-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0003_alter_palabras_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='nombre',
            field=models.CharField(default='Reporte sin nombre', editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
