# Generated by Django 5.2 on 2025-04-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0005_provincia_empresa_ruc_empresa_provincia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conteo',
            new_name='ConteoTotal',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Palabras.empresa'),
        ),
    ]
