# Generated by Django 5.2 on 2025-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0006_rename_conteo_conteototal_alter_reporte_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='anio',
            field=models.IntegerField(default=2025),
        ),
    ]
