# Generated by Django 5.2 on 2025-04-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0006_archivozip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='zips/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
