# Generated by Django 5.2 on 2025-04-30 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Palabras', '0007_ziparchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Palabras.empresa'),
        ),
    ]
